#!/usr/bin/env python3

import argparse
import angr

from serializers import VectreProgDefSerializer


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="BIL to UCLID5 Transpiler to check secure speculation.")
    parser.add_argument("binary_file_path")
    parser.add_argument("output_file_path")
    args = parser.parse_args()
    binary_file_path = args.binary_file_path
    output_file_path = args.output_file_path

    # ANGR experiments
    proj = angr.Project(binary_file_path)
    serializer = VectreProgDefSerializer(proj)
    vectre_spec = serializer.serialize_binary()

    with open(output_file_path, 'w+') as f:
        f.write(vectre_spec)



