#!/usr/bin/env python3

import argparse

from serializers.utils import print_blocks
from transpiler import VectreDisassembler

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="BIL to UCLID5 Transpiler to check secure speculation.")
    parser.add_argument("binary_file_path")
    parser.add_argument("output_file_path")
    args = parser.parse_args()
    binary_file_path = args.binary_file_path
    output_file_path = args.output_file_path

    # Create parser
    sst = VectreDisassembler()
    sst.read_binary(binary_file_path)

    # Create UCLID5
    # TODO: Arguments to parser can be unroll or induction
    sst.transpile(output_file_path)
