from string import Template

program_template = Template("module program {\n"
                            "    type * = common.*;\n"
                            "    const * = common.*;\n"
                            "    function * = common.*;\n"
                            "    definition * = common.*;\n\n"
                            ""
                            "    input spec_enabled : boolean;\n"
                            "    var next_block : block_id_t;\n"
                            "    instance uarch : uarchitecture(spec_enabled : (spec_enabled));\n\n"
                            ""
                            "    ${CFG_BLOCKS}\n\n"
                            ""
                            "    init {\n"
                            "        next_block = beginning;\n"
                            "    }\n\n"
                            "    next {\n"
                            "        if (uarch.spec_level != common.spec_idx0 && common.br_resolve(br_pred_state, pc)) {\n"
                            "            call uarch.do_resolve();\n"
                            "        } else {\n"
                            "            case\n"
                            "                ${CFG_EDGES)\n"
                            "                (next_block == end) : {}\n"
                            "            esac\n"
                            "        }\n"
                            "    }\n\n"
                            "}")